name: shared_ui
description: Shared UI components, themes, and services for Maritime Procurement ERP Flutter apps
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.4.0
  
  # UI Components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  
  # Utilities
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  uuid: ^4.4.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Forms & Validation
  formz: ^0.7.0
  equatable: ^2.0.5
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
