name: tech_app
description: Maritime Procurement ERP - Technical Portal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Shared UI Package
  shared_ui:
    path: ../../packages/shared_ui
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.4.0
  
  # UI Components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  
  # Utilities
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  uuid: ^4.4.0
  
  # Navigation
  go_router: ^13.0.0
  sidebarx: ^0.17.2
  
  # Forms & Validation
  formz: ^0.7.0
  
  # Icons
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2874.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets (commented out until assets are added)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts (using Google Fonts instead)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700